version: '3'

services:
  application:
    image: blackikeeagle/swarm-sample-php
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s

  nginx:
    image: blackikeeagle/swarm-sample-nginx
    ports:
      - "80:80"
